Header
aemsites/audi pull request #15
Opened 2024-03-06 02:17 UTC by shsteimer

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.live/
- After: https://<branch>--{repo}--{owner}.hlx.live/

2024-03-06 02:18 UTC, shsteimer commented on aemedge/blocks/header/header.js
> +  }
@kunwarsaluja here's how I'm fetching header json with a local fallback, incase you want to do similar for footer.

2024-03-08 14:15 UTC, kunwarsaluja approved these changes, later dismissed
Looks and works pretty good overall. Some tiny callouts if we want to do it now or in other issue #27 both works, See below screenshot

1. Header covers the full screen width in high viewpoints
**Live site**
![Screenshot 2024-03-08 at 9 09 50 AM](https://github.com/aemsites/audi/assets/10811320/91259ffc-ecd6-4898-b624-bc833ff825d8)

**Edge Delivery**
![Screenshot 2024-03-08 at 9 08 36 AM](https://github.com/aemsites/audi/assets/10811320/2d9ad094-55bc-49eb-8d4c-7b9105ceaeac)

2. in Mobile view, once i click a sub-menu like Models, there is transition at open and close of the menu underneath. Transition at open doesnt work but close does.

3. Header is Audi live site isn't sticky when scrolled so we need to remove the styling around it.

2024-03-08 15:36 UTC, kunwarsaluja requested changes
See comments

2024-03-08 16:45 UTC, shsteimer commented
@kunwarsaluja all 3 things should now be resolved

2024-03-08 16:48 UTC, kunwarsaluja approved these changes

2024-03-08 16:49 UTC, merged